### ISSUE TITLE
overwrites PKG_CONFIG_PATH incorrectly (08/23/12)

### ISSUE THREAD

**Issue by mirzashah** [ros/rospack#1]
Migrated from code.ros.org, issue #4034 
Reported by:    bedahr
https://code.ros.org/trac/ros/ticket/4034

Description 

Today, while setting up ROS on a Gentoo system, I encountered the problem that rospack did not find a package that pkg-config, when invoked directly, would find just fine: bedahr@eucleia ~/ros $ /opt/ros/fuerte/bin/rospack cflags-only-I rosjava_jni Package roscpp was not found in the pkg-config search path. Perhaps you should add the directory containing `roscpp.pc' to the PKG_CONFIG_PATH environment variable No package 'roscpp' found bedahr@eucleia ~/ros $ pkg-config --cflags roscpp -I/opt/ros/fuerte/include

After a lot of messing about, I found out that something in rospack seems to overwrite PKG_CONFIG_PATH to a relative path related to the location of the package. For std_msgs this resulted in: PKG_CONFIG_PATH=/opt/ros/fuerte/share/std_msgs/../../lib/pkgconfig But for roscpp, which was installed in the users installation path, this became: PKG_CONFIG_PATH=/home/bedahr/ros/roscpp/../../lib/pkgconfig

It's worth mentioning that even locally installed packages seem to install the .pc file to /opt/ros/fuerte/lib/pkgconfig

As a fix, I would suggest to simply append to instead of overwriting PKG_CONFIG_PATH.

**Comment by dirk-thomas** [comment]
Based on the description I can not completely follow what the workflow and based on that the problem is.

All .pc files are generated in devel/install space under lib/pkg-config. That seems to be intended and correct behavior. catkin also only prepends paths to the PKG_CONFIG_PATH and never overwrites it.

If the issue is still valid please comment with more detailed information about your environment, the steps to reproduce and the actual as well as expected behavior.
