### ISSUE TITLE
rospack depends-indent -- If there is a cycle, only prints error but not packages (which would be useful for debugging)

### ISSUE THREAD

**Issue by eacousineau** [ros/rospack#18]
Per this [post](https://github.com/ros/rospack/issues/2#issuecomment-20201122), I tried out `rospack depends-indent` in ROS Fuerte, but it did not print out a list of packages if there was a cycle.

The usage outlined by Brian Gerkey would definitely help in this situation.

Package: ros-fuerte-rospack (2.0.13-1precise-20120908-1622-+0000)

**Comment by dirk-thomas** [comment]
How is this issue different than #2?

**Comment by eacousineau** [comment]
The suggestion in #2 was to use depends-indent of rospack to manually find the circular dependency, but when I tried it, it did not produce the output necessary.
I figured that this was a little more specific than #2 and had some different scope, but I can delete this issue and merge the bug report into that one if you like.

**Comment by dirk-thomas** [comment]
I will commit a patch to rospack (Grooby and Hydro) soon which will add the package names involved in the circular dependency to the exception string. But the patch will very likely not be backported to Fuerte since it is not a critical bug fix and would require to rebuild and redeploy to many packages.
