### ISSUE TITLE
Prevent recursion in ROS_ROOT/ROS_PACKAGE_PATH ?

### ISSUE THREAD

**Issue by tho-** [ros/rospack#23]
Recursion in ROS_ROOT/ROS_PACKAGE_PATH is pretty much useless now, since AFAIK all package.xml are located in the top-level subdirectory of each package.

Recursion is costly. For instance, with ROS_PACKAGE_PATH=${HOME}/openrobots/i386-ubuntu1204/share (NFS mounted), i get the following figures:

```
% rospack profile
Full tree crawl took 13.936435 seconds.
[...]
-------------------------------------------------------------
13.281717   /home/mallet/openrobots/i386-ubuntu1204/share
4.857618 * /home/mallet/openrobots/i386-ubuntu1204/share/doc
4.087676 * /home/mallet/openrobots/i386-ubuntu1204/share/blender
```

I know that rospack will skip "rospack_nosubdir" files, but in my case I don't want to pollute external packages (like 'blender' above) with alien files :)

What about turning ROS_PACKAGE_PATH into a "no-recursion" by default (as for every other PATH variable like PYTHONPATH), and maybe enabling the recursion with a special syntax like double / ending or maybe a trailing `/*` (like in TEXINPUTS) such as:

ROS_PACKAGE_PATH=/path/recurse/me//:/path/do/not/recurse
or
ROS_PACKAGE_PATH=/path/recurse/me/*:/path/do/not/recurse

(or the opposite: a special syntax to not recurse, like ROS_PACKAGE_PATH=/path/do/not/recurse/--:/path/recurse/me )

what do you think?

EDIT: one level of recursion is still of course wanted, since given a /path/to/dir one wants to find /path/to/dir/pkg1/package.xml, but I think you got my idea anyway :)

**Comment by tkruse** [comment]
To give more context to the problem at hand. robotpkg is a collection of robotic software coming with a centralized package manager. It includes many non-ROS packages and some base ROS packages (roughly ros-deskop variant). It installs both ROS and non-ROS packages to a common folder with FHS layout, meaning the share/ folder will have both ROS packages as well as other software files (e.g. blender). The ROS_PACKAGE_PATH (RPP) is currently set by robotpkg to the share folder, but this causes unnecessary delays due to rospack recursive crawling of large non-ROS folders. 

The question is how ROS and non-ROS packages can best be installed in the same FHS folder layout without running into those rospack recusrion delays. While this is for now a niche problem, it still concerns the whole community in the progress towards installing ROS to /usr in general.

Changing the RPP semantics is a brainstorming suggestion.

Workarounds would be:
- to not put share/ itself in the RPP, but only ROS package subfolders
- adding rospack_nosubdir files into all non-ROS share subfolders as mentioned
- not installing ROS and non-ROS packages into the same folder to start with.

Other solutions (for the mere sake of brainstorming) are marker files indicating subfolders to ignore, or RPP elements indicating subfolders to ignore.

**Comment by tho-** [comment]
To me "adding rospack_nosubdir files into all non-ROS share subfolders" is a no-go: one package (rospack) should not pollute/disturb other packages :)

An alternative workaround could be : install ROS packages into share/ros/pkg instead of share/pkg.

But I'd also like to have comments (or pointers to some doc) on the necessity of having a recursive ROS_PACKAGE_PATH at all.

**Comment by tkruse** [comment]
The two main needs I see are for recursive package crawling are rosbuild and source-space runtime environments.

With rosbuild, even installed packages can be in nested subfolders, e.g.:

```
$ rospack find move_base
/opt/ros/groovy/stacks/navigation/move_base
```

Source-space runtime environments exists with both rosbuild and catkin. E.g. creating a catkin workspace, you get this:

```
groovy_underlay $ . devel/setup.bash
$ echo $ROS_PACKAGE_PATH 
/home/kruset/groovy_underlay/src
```

In order for rosbuild packages to resolve package resource then, the groovy_underlay/src needs to be crawled for packages, which may be nested deeply.

Not sure whether I miss some other important reason for keeping recursive semantics of the RPP as the default.

**Comment by dirk-thomas** [comment]
Changing the semantic of the ROS_PACKAGE_PATH is nothing which can be done at that point without affecting (and likely breaking) the setup of every ROS user. So the chances that this proposal is realized in any ROS release in the near future is pretty much zero.

The point that crawling the filesystem recursively is inefficient is valid. It will definitely be considered for new development.

**Comment by tkruse** [comment]
@tho- : Maybe you can install to openrobot/opt/ros/fuerte/ instead? This could make it easier for users to distinguish between a robopkg installation of ROS and a debian-package installation.

Also note that while catkin packages generate FHS compliant layout this does not mean that package maintainers have already selected nice (unique, self-explaining) names for headers, executables and libraries to play along in a larger FHS ecosystem, so installing to openrobots directly may not be a wise choice in any case. I wont recommend either way, as every solution has pros and cons.

@dirk-thomas 
The RPP currently allows having path entries which do not exist (Will be ignored). And thus extending the RPP with a syntax for paths that are sufficiently unlikely to exist and be part of the RPP, but are still valid paths, would not break anything (but be dirty). Just saying this for the sake of brainstorming, and because for the sake of installing ROS to /usr one day may require some change like this. However some smarter rospack caching strategy might be the better solution.

@dirk-thomas : I assume that since you did not add another alternative to avoid rospack crawling in the robotpkg scneario, you don't see any other than those I listed?

I for one agree the default semantics for valid and existing paths should not be touched IMO, so this issue can probably be closed, if @tho- agrees?

**Comment by tho-** [comment]
On Friday, at 02:40, tkruse wrote:
| @tho- : Maybe you can install to openrobot/opt/ros/fuerte/ instead? This could make
| it easier for users to distinguish between a robopkg installation of ROS and a
| debian-package installation.

The goal is exactly the opposite: make it transparent :) Also, having a opt/ros
prefix inside the /opt/openrobots prefix is a bit messy and more complex to
handle (users have to setup several PATH, PYTHONPATH etc.).

Actually, robotpkg used to install ros in <prefix>/opt/ros/fuerte, but since
groovy is much cleaner regarding the FHS, it is now ok to install directly into
<prefix>, which is the goal of being FHS-compliant :) The only local patch is
the move of env.sh + setup.sh into <prefix>/etc/ros/.

| Also note that while catkin packages generate FHS compliant layout this does not
| mean that package maintainers have already selected nice (unique, self-explaining)
| names for headers, executables and libraries to play along in a larger FHS

Sure. If such packages are to be included in robotpkg, then those package would
be fixed either via local patches or upstream. And in any case, any problematic
package can still be installed into a <prefix>/opt/stuff prefix, even though
ros-{base,desktop} packages are in <prefix>.

| I for one agree the default semantics for valid and existing paths should not be
| touched IMO, so this issue can probably be closed, if @tho- agrees?

The existing semantics is of course not to be changed. However, since there is
a consensus on the fact that recursive crawling is bad, it would be better not
to close the issue until a solution has been found?

**Comment by tkruse** [comment]
So, the idea would be to indeed introduce a special syntax for entries in the RPP, such that existing paths will be treated as usual by recursive crawling through all nested subdirectories looking for package manifests, while non-existing paths with a special marker syntax will be resolved to decoded paths, which, if exist, will only be cawled for package manifests one level deep.

In the opening example, with `/home/mallet/openrobots/i386-ubuntu1204/share<SPECIAL-SUFFIX>` in the RPP, the directories
`/home/mallet/openrobots/i386-ubuntu1204/share/doc` and
`/home/mallet/openrobots/i386-ubuntu1204/share/blender` would be searched for package manifests, but none of their subfolders would.

As an example, using `/NO-RECURSE` as special suffix:

```
 ROS_PACKAGE_PATH=/home/user/catkin_ws/install/share/NO-RECURSE:/home/user/rosbuild_ws:/opt/ros/hydro/share/NO-RECURSE:/opt/ros/hydro/stacks
```

will find any package anywhere below `/home/user/rosbuild_ws` and `/opt/ros/hydro/stacks`, but only packages one level deep in `/home/user/catkin_ws/install/share` and `/opt/ros/hydro/share/`, reducing rospack crawling time substantially depending on what else lives in those share folders. 

Should a folder named NO-RECURSE be placed inside one of the latter two folders, then the full path would be used, which would be an undesired corner-case. Alternatively, NO-RECURSE could be an ignored suffix.

Introducing such a change would not affect existing ROS installations (unless they use NO-RECURSE as folder name). However, unless backported, users adopting the new notation for an old ROS distribution might be surprised.

Things to consider for the special syntax:
- non-recursive entries should still form valid paths on targeted operating systems (win, Mac, *nix)
- the format should attemt to be self-explaining
- the format should not be confusable with other shell-ish syntax
- the added symbols should be short to avoid too much polution of debugging output

so these symbols should be avoided: `: .*?|<>:"/\'%#~`

Some other suggestions for marker suffixes:
foo/!
foo/NR
foo/---
foo/^

Some other alternatives without modifying the RPP (none entirely tongue-in-cheek):
- rospack could treat any folder named "share" this special way always (Still low probability of breaking stuff)
- don't care about this problem and deprecate rospack and rosbuild, then dump them regardless of losing all rosbuild-based packages
- never install ROS to /usr and ignore people trying to do that or similar things

So one way to push this further would be to point the buildsystem SIG to this issue:
https://groups.google.com/forum/?fromgroups=#!forum/ros-sig-buildsystem
if opinions are favorable create a REP justifying the change in light of the problem and the alternatives, then put the REP to vote on ros-users.
Another way would be for OSRF to just implement the change as a necessary step towards installing ROS in /usr.

@tfoote : Thoughts?

**Comment by tfoote** [comment]
Changing the ROS_PACKAGE_PATH is definitely in scope for a new REP.  I
think that we should not just do this as a patch but review the RPP
entirely and make any changes we want to consider for the future and have
RPP well documented in a REP.  Getting ROS into /usr is going to be a long
process with a lot of steps we shouldn't hurry in a quick fix.

**Comment by dirk-thomas** [comment]
As @tfoote commented before this conception change requires a REP. Until then I will close this ticket since no action on rospack will be taken until then.
