### ISSUE TITLE
Errors when including rospack/rospack.h

### ISSUE THREAD

**Issue by bit-pirate** [ros/rospack#37]
I wanted to use the `Rospack` class from rospack, but once I included the header, I got the following error:

```
/opt/ros/hydro/include/rospack/rospack.h:521:1: error: expected identifier before string constant
/opt/ros/hydro/include/rospack/rospack.h:521:1: error: expected ‘,’ or ‘...’ before string constant
/opt/ros/hydro/include/rospack/rospack.h:520:10: error: invalid use of ‘::’
/opt/ros/hydro/include/rospack/rospack.h:529:1: error: expected identifier before string constant
/opt/ros/hydro/include/rospack/rospack.h:529:1: error: expected ‘,’ or ‘...’ before string constant
/opt/ros/hydro/include/rospack/rospack.h:528:10: error: invalid use of ‘::’
```

**Comment by tfoote** [comment]
For reference I believe it's this line: https://github.com/ros/rospack/blob/indigo-devel/include/rospack/rospack.h#L521

This sounds like a symbol collision. Do you have the problem if you include rospack.h alone or first?

**Comment by dirk-thomas** [comment]
Could you please provide more information? E.g. a simple main.cpp file which exhibits the problem.

**Comment by bit-pirate** [comment]
> Could you please provide more information? E.g. a simple main.cpp file which exhibits the problem.

Sure, see below. The strange thing is, there seems to be a conflict with rosbag. Including rospack **after** a header from rosbag leads to the reported error. Including it before works fine.

```
#include <ros/ros.h>
#include <rosbag/bag.h> // or <rosbag/view.h>
#include <rospack/rospack.h>

int main (int argc, char** argv)
{
  ros::init(argc, argv, "rospack_test");
  return 0;
}
```

**Comment by dirk-thomas** [comment]
This is sadly nothing `rospack` can address. `console_bridge` (which is used by `rosbag` internally defines e.g. `logWarn` (https://github.com/ros/console_bridge/blob/7aebc3367b4945d9963457549026ea137b047b7b/include/console_bridge/console.h#L68) which collides with the already long existing API of `rospack`.

I have filled a ticket against ros/console_bridge#18. I will mark this as closed since we can't just change the `rospack` API because of that.
