### ISSUE TITLE
'boost/tr1/unordered_set.hpp' file not found

### ISSUE THREAD

**Issue by shivamkumarsingh114** [ros/rospack#92]
I understand that new versions of boost don''t have tr1 file but in Kinetic-devel branch it is still included in the code which throws this error.
since lunar is still not supported for OSX I am trying to install Kinetic with No avail.
OSX: 10.13
ROS-Kinetic

![screenshot 2018-08-29 at 10 41 31 pm](https://user-images.githubusercontent.com/23401023/44803664-b30e1700-abdc-11e8-8e73-fcc369d66595.png)

**Comment by dirk-thomas** [comment]
In the Boost version(s) available on the platforms targeted by Kinetic the `tr1` headers are present. `tr1` was removed on the lunar-devel branch in #80 since newer Boost version don't provide the `tr1` headers anymore.

> since lunar is still not supported for OSX I am trying to install Kinetic with No avail.

macOS is a rolling release. When installing dependencies with Homebrew you will get the latest version of Boost. As a consequence I would recommend to use the latest ROS distro.

I am not sure why you think that Lunar (or Melodic) are not supported on macOS? [This discourse post](https://discourse.ros.org/t/ros-lunar-on-os-x/2967) sounds like it should work.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket assuming my previous comment resolved the problem.

**Comment by GiulioPettenuzzo** [comment]
I am in the same situation, but I don't understand how to solve it!

**Comment by DaHaiHuha** [comment]
I want to know the solution, what if i just download 'boost/tr1/unordered_set.hpp' file and put it the right place?

**Comment by daweim0** [comment]
Did that work?

**Comment by jveitchmichaelis** [comment]
There are issues with ROS Melodic on Arm64 and Kinetic is the last known good version for my application. I've added a PR to fix this that should retain back-compatibility with previous versions of boost (the problem was only introduced with 1.65 I believe). I've tested this in Debian buster and it passes the Xenial test suite.

If this is a wontfix, then others can use my patch here: https://github.com/jveitchmichaelis/rospack/tree/kinetic-fix-boost
